import fs from 'node:fs';
import path from 'node:path';
const root = path.resolve('skills/brand-suite');
const write = (p,x) => {fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(x,null,2)+'\n');};
const input = fs.existsSync('REFERENCE_DOCUMENT_CATALOGUE.json')?JSON.parse(fs.readFileSync('REFERENCE_DOCUMENT_CATALOGUE.json','utf8')):{documents:JSON.parse(fs.readFileSync(path.join(root,'templates/catalogue.json'),'utf8')).documents.map(d=>({id:d.id,reference_title:d.title,folder:d.folder,required_formats:d.formats,reference_section_coverage:d.sections}))};
write(path.join(root,'templates/catalogue.json'),{version:'1.0.0', documents:input.documents.map(d=>({id:d.id,title:d.reference_title,folder:d.folder,formats:d.required_formats,sections:d.reference_section_coverage,applicability:d.id[0]==='C'?'entity-and-authority-review':d.id[0]==='P'?'workforce-review':'context-review',risk_gates:['factual','visual',...(/[PACF]/.test(d.id[0])?['local-legal','authority']:[])],inapplicable:'three-format applicability note',required_fields:['company.trading_name'],optional_fields:['company.registration_identifier']}))});
const scalar={type:['string','number','boolean','null']};
const field={type:'object',additionalProperties:false,required:['value','status','source_id','locator','observed_at','sha256','scope','verification'],properties:{value:scalar,status:{enum:['VERIFIED_PRIMARY','OWNER_PROVIDED','IMPLEMENTATION_OBSERVED','PUBLICLY_CLAIMED','PROPOSED','CONFLICTED','UNKNOWN']},source_id:{type:['string','null']},locator:{type:['string','null']},observed_at:{type:'string'},sha256:{type:['string','null'],pattern:'^[a-f0-9]{64}$'},scope:{type:'string',minLength:1},verification:{type:'string',minLength:1}}};
const fields={type:'object',propertyNames:{pattern:'^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*)+$'},additionalProperties:field};
const block={type:'object',additionalProperties:false,required:['id','type','category'],properties:{id:{type:'string',pattern:'^[A-Za-z0-9_-]+$'},type:{enum:['heading','paragraph','list','table','image','signature','note','page-break']},category:{enum:['fact','proposed-term','review','design','instruction']},text:{type:'string'},level:{enum:[1,2,3]},items:{type:'array',items:{type:'string'}},rows:{type:'array',items:{type:'array',items:{type:'string'}}},src:{type:'string'},alt:{type:'string'},width_mm:{type:'number',minimum:1,maximum:170},height_mm:{type:'number',minimum:1,maximum:230},reference:{type:'string'}}};
const record=(properties,required=Object.keys(properties))=>({type:'object',additionalProperties:false,properties,required});
const str={type:'string'}, array={type:'array',items:{type:'object'}}, stringArray={type:'array',items:str};
const schemas={
 'input':record({schema_version:{const:'1.0'},mode:{enum:['full-suite','audit-only','stationery-only','update-existing','validate-existing']},language:{enum:['en']},paper:{enum:['A4','Letter']},entity_id:{type:'string',minLength:1},fictional:{type:'boolean'},fields,brand:record({primary:{type:'string',pattern:'^#[a-fA-F0-9]{6}$'},ink:{type:'string',pattern:'^#[a-fA-F0-9]{6}$'},accent:{type:'string',pattern:'^#[a-fA-F0-9]{6}$'},font:str,logo:{type:['string','null']},logo_rights:str,stamp_company_mm:{type:'number',minimum:30,maximum:80},stamp_signatory_mm:{type:'array',minItems:2,maxItems:2,items:{type:'number',minimum:15,maximum:100}}}),sources:{type:'array',items:record({id:str,kind:{enum:['owner','file','official','public','synthetic']},locator:str,sha256:{type:['string','null']},scope:str})},reviewed_paths:array,contradictions:array,website:record({authorized:{type:'boolean'},url:{type:['string','null']},budget:{type:'integer',minimum:1,maximum:50}}),applicability:{type:'object',additionalProperties:record({applicable:{type:'boolean'},reason:str,title:{type:['string','null']}})},terms:{type:'object',additionalProperties:scalar},finance:record({currency:{enum:['USD','GBP','EUR','PKR','JPY','KWD']},precision:{enum:[0,2,3]},items:{type:'array',items:record({description:str,quantity:{type:'integer',minimum:1,maximum:100000},unit_price:{type:'string',pattern:'^\\d+(\\.\\d+)?$'}})},tax:{type:['string','null'],pattern:'^\\d+(\\.\\d+)?$'},paid:{type:'string',pattern:'^\\d+(\\.\\d+)?$'},payment_status:{enum:['UNVERIFIED','OBSERVED_RECEIVED','SETTLED']}}),model_overrides:{type:'object',additionalProperties:{type:'array',items:block}},prior:{type:['string','null']}}),
 'document-model':record({schema_version:{const:'1.0'},id:str,title:str,folder:str,paper:{enum:['A4','Letter']},applicability:record({applicable:{type:'boolean'},reason:str}),release_state:{enum:['DRAFT_TEMPLATE','BLOCKED_MISSING_FACTS','READY_FOR_REVIEW','APPROVED_BY_AUTHORIZED_REVIEWER']},entity_id:str,header:str,footer:str,blank:{type:'boolean'},blocks:{type:'array',items:block},fields_used:stringArray,unresolved:stringArray,review_requirements:stringArray,template_version:str}),
 'company-profile':record({schema_version:{const:'1.0'},entity_id:str,fictional:{type:'boolean'},fields}),
 'brand-tokens':record({schema_version:{const:'1.0'},fields,geometry:record({margin_mm:{const:22},body_pt:{const:11},footer_pt:{const:9},paper:{enum:['A4','Letter']}}),provisional:{type:'boolean'}}),
 'source-register':record({schema_version:{const:'1.0'},sources:array}),
 'evidence-map':record({schema_version:{const:'1.0'},claims:array}),
 'unknowns':record({schema_version:{const:'1.0'},fields:stringArray}),
 'contradictions':record({schema_version:{const:'1.0'},items:array}),
 'website-coverage':record({schema_version:{const:'1.0'},budget:{type:'integer'},pages:array,unreviewed:stringArray,mode:str}),
 'catalogue':record({version:str,documents:{type:'array',minItems:36,maxItems:36,items:record({id:{type:'string',pattern:'^[GS PACF][0-9]{2}$'},title:str,folder:str,formats:{const:['html','pdf','docx']},sections:stringArray,applicability:str,risk_gates:stringArray,inapplicable:str,required_fields:stringArray,optional_fields:stringArray})}}),
 'approval-record':record({schema_version:{const:'1.0'},state:{const:'NOT_APPROVED'},reviewer:{type:'null'},evidence:{type:'null'},reason:str}),
 'field-registry':record({schema_version:{const:'1.0'},fields:array}),
 'manifest':record({schema_version:{const:'1.0'},mode:str,complete:{type:'boolean'},entity_id:str,input_hash:str,documents:array,artifacts:array,blockers:stringArray}),
};
for(const [name,schema] of Object.entries(schemas)) write(path.join(root,'schemas',name+'.schema.json'),{$schema:'http://json-schema.org/draft-07/schema#',...schema});
