import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';import assert from 'node:assert/strict';import {json,writeJson,fileHash,hash} from '../skills/brand-suite/lib/safety.mjs';
const root=process.cwd(),repo=process.argv[2];if(!repo||!/^[-\w]+\/[-\w]+$/.test(repo))throw Error('Supply verified GitHub owner/repository');
import {npmCLI} from './npm-cli.mjs';
const work=fs.mkdtempSync(path.join(os.tmpdir(),'brand-suite-remote-')),cli=path.join(root,'node_modules/skills/bin/cli.mjs'),npm=npmCLI();
function command(bin,args,timeout=300000){const r=spawnSync(bin,args,{cwd:work,encoding:'utf8',windowsHide:true,timeout,maxBuffer:4_000_000,env:{...process.env,DISABLE_TELEMETRY:'1'}});if(r.status!==0)throw Error(r.stderr+'\n'+r.stdout);return r.stdout;}
const sha=command('gh',['api','repos/'+repo+'/commits/main','--jq','.sha']).trim();
const listing=command(process.execPath,[cli,'add',repo,'--list']);assert.match(listing,/brand-suite/);
command(process.execPath,[cli,'add',repo,'--skill','brand-suite','--agent','codex','--yes','--copy']);const installed=path.join(work,'.agents/skills/brand-suite');assert.ok(fs.existsSync(path.join(installed,'SKILL.md')));console.log('Remote listing and project-scoped copy installation passed');
const resources=[];for(const p of ['scripts/brand-suite.mjs','scripts/production.py','templates/catalogue.json','templates/documents/clauses.mjs','schemas/input.schema.json','references/brand-principles.md']){const original=spawnSync('git',['show',sha+':skills/brand-suite/'+p],{cwd:root,encoding:'utf8',windowsHide:true});assert.equal(original.status,0);assert.equal(fs.readFileSync(path.join(installed,p),'utf8').replaceAll('\r\n','\n'),original.stdout.replaceAll('\r\n','\n'));resources.push({path:p,sha256:fileHash(path.join(installed,p))});}
command(process.execPath,[npm,'ci','--ignore-scripts','--prefix',installed]);const doctor=JSON.parse(command(process.execPath,[path.join(installed,'scripts/brand-suite.mjs'),'doctor']));assert.equal(doctor.supported_production,true);
const evidence=path.join(work,'evidence');fs.cpSync(path.join(root,'tests/fixtures/codebase'),evidence,{recursive:true});const before=['README.md','routes.js','theme.css'].map(p=>fileHash(path.join(evidence,p)));const logo=path.join(work,'logo.svg');fs.copyFileSync('tests/fixtures/logo.svg',logo);const input=json('tests/fixtures/full.json');input.brand.logo=logo;writeJson(path.join(work,'input.json'),input);
console.log('Downloaded resources match pushed commit; generating full suite');
const output=path.join(work,'suite'),result=JSON.parse(command(process.execPath,[path.join(installed,'scripts/brand-suite.mjs'),'build','--input',path.join(work,'input.json'),'--target',evidence,'--out',output],600000));assert.equal(result.baseline_artifacts,108);assert.equal(result.technical_pass,true);assert.deepEqual(before,['README.md','routes.js','theme.css'].map(p=>fileHash(path.join(evidence,p))));
const report={timestamp:new Date().toISOString(),repository:repo,commit:sha,cli:'skills 1.7.0',remote_listing:true,remote_copy_install:true,agent:'codex',project_scope:true,resource_hashes:resources,baseline_artifacts:108,technical_pass:true,target_unchanged:true,execution_approved:false,environment:{platform:process.platform,node:process.version,document_renderer:doctor.dependencies.document_renderer,browser:doctor.dependencies.browser},visual_review:'NOT RUN for this independent smoke build; local release example PDFs have their own complete visual ledger'};writeJson(path.join(root,'docs/results/remote-install.json'),report);console.log(JSON.stringify(report));
